CREATE DATABASE IF NOT EXISTS app_reservas;

USE app_reservas;

CREATE TABLE IF NOT EXISTS Rooms(
  room_id INT NOT NULL,
  PRIMARY KEY (room_id)
);

CREATE TABLE IF NOT EXISTS Users(
  email VARCHAR(64) NOT NULL,
  name VARCHAR(32) NOT NULL,
  last_name VARCHAR(32) NOT NULL,
  authorized BOOLEAN NOT NULL,
  PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS Admins(
  email VARCHAR(64) NOT NULL,
  PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS Login(
  email VARCHAR(64) NOT NULL,
  password VARCHAR(256) NOT NULL,
  PRIMARY KEY (email),
  FOREIGN KEY (email) REFERENCES Users(email)
);
