### Send POST request with json body
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "martin.caraballo@correo.ucu.edu.uy",
  "password": "123456789",
  "name": "Martin",
  "lastName": "Caraballo",
  "phoneNumber": "099 677 264"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "martin.caraballo@correo.ucu.edu.uy",
  "password": "123456789"
}