###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "MGcc2003@@"
}

> {% client.global.set("auth_token", response.headers.valueOf("Authorization").split("Bearer ")[1]); %}

###
GET http://localhost:8080/week
#Authorization: Bearer {{auth_token}}

###
GET http://localhost:8080/reserve?roomId=1
Authorization: Bearer {{auth_token}}